import type { AiDifficulty, CardRarity, SkillCardType } from "./types";

export const BOARD_SIZE = 15;
export const DEFAULT_WIN_LENGTH = 5;
export const MAX_HAND_SIZE = 8;

export const RARITY_CONFIG: Record<
  CardRarity,
  { label: string; color: string; dropRate: string }
> = {
  common: { label: "Thường", color: "#94a3b8", dropRate: "~49%" },
  rare: { label: "Hiếm", color: "#38bdf8", dropRate: "~29%" },
  epic: { label: "Sử thi", color: "#c084fc", dropRate: "~17%" },
  legendary: { label: "👑 Vua", color: "#fbbf24", dropRate: "~5%" },
};

export type SkillMeta = {
  icon: string;
  name: string;
  description: string;
  hint: string;
  success: string;
  border: string;
  face: string;
  accent: string;
  foil: string;
  artBg: string;
  rarity: CardRarity;
  deckCopies: number;
  instant?: boolean;
};

export const SKILL_META: Record<SkillCardType, SkillMeta> = {
  block: {
    icon: "🚫",
    name: "Phong Ấn",
    description: "Khóa 1 ô — đối thủ không đặt được.",
    hint: "Chọn ô trống.",
    success: "Ô đã bị phong ấn!",
    border: "#94a3b8",
    face: "#141c28",
    accent: "#cbd5e1",
    foil: "linear-gradient(135deg, #e2e8f0, #64748b, #fff, #475569)",
    artBg: "linear-gradient(160deg, #1e293b, #64748b, #0f172a)",
    rarity: "common",
    deckCopies: 5,
  },
  swap: {
    icon: "🔀",
    name: "Hoán Đổi",
    description: "Dịch chuyển quân ○ sang ô trống.",
    hint: "Chọn quân ○, rồi ô đích.",
    success: "Hoán đổi thành công!",
    border: "#34d399",
    face: "#042f23",
    accent: "#6ee7b7",
    foil: "linear-gradient(135deg, #6ee7b7, #10b981, #fff, #047857)",
    artBg: "linear-gradient(160deg, #064e3b, #34d399, #022c22)",
    rarity: "common",
    deckCopies: 5,
  },
  scout: {
    icon: "👁️",
    name: "Trinh Sát",
    description: "Lộ nước đi tốt nhất của AI trên bàn.",
    hint: "Kích hoạt ngay.",
    success: "Đã lộ nước AI!",
    border: "#a8a29e",
    face: "#292524",
    accent: "#d6d3d1",
    foil: "linear-gradient(135deg, #d6d3d1, #78716c, #fff, #44403c)",
    artBg: "linear-gradient(160deg, #44403c, #a8a29e, #1c1917)",
    rarity: "common",
    deckCopies: 5,
    instant: true,
  },
  unseal: {
    icon: "🔓",
    name: "Mở Khóa",
    description: "Gỡ phong ấn 1 ô.",
    hint: "Chọn ô đang bị phong ấn.",
    success: "Đã mở khóa ô!",
    border: "#cbd5e1",
    face: "#1e293b",
    accent: "#e2e8f0",
    foil: "linear-gradient(135deg, #e2e8f0, #94a3b8, #fff, #64748b)",
    artBg: "linear-gradient(160deg, #334155, #cbd5e1, #0f172a)",
    rarity: "common",
    deckCopies: 5,
  },
  peek: {
    icon: "🔮",
    name: "Tiên Tri",
    description: "Xem 3 lá tiếp theo trong bộ bài.",
    hint: "Kích hoạt ngay.",
    success: "Đã xem lá tới!",
    border: "#c4b5fd",
    face: "#2e1065",
    accent: "#ddd6fe",
    foil: "linear-gradient(135deg, #ddd6fe, #a78bfa, #fff, #6d28d9)",
    artBg: "linear-gradient(160deg, #4c1d95, #c4b5fd, #1e1b4b)",
    rarity: "common",
    deckCopies: 5,
    instant: true,
  },
  blink: {
    icon: "💫",
    name: "Nhảy Cóc",
    description: "Hoán vị 2 quân ○.",
    hint: "Chọn quân ○ thứ nhất.",
    success: "Đã hoán vị 2 quân!",
    border: "#67e8f9",
    face: "#083344",
    accent: "#a5f3fc",
    foil: "linear-gradient(135deg, #a5f3fc, #22d3ee, #fff, #0891b2)",
    artBg: "linear-gradient(160deg, #164e63, #67e8f9, #042f2e)",
    rarity: "common",
    deckCopies: 5,
  },
  mend: {
    icon: "✨",
    name: "Sửa Khiên",
    description: "Gỡ khiên bảo vệ khỏi 1 quân ○.",
    hint: "Chọn quân ○ có khiên.",
    success: "Đã gỡ khiên!",
    border: "#86efac",
    face: "#052e16",
    accent: "#bbf7d0",
    foil: "linear-gradient(135deg, #bbf7d0, #4ade80, #fff, #15803d)",
    artBg: "linear-gradient(160deg, #14532d, #86efac, #052e16)",
    rarity: "common",
    deckCopies: 5,
  },
  mark: {
    icon: "📍",
    name: "Dấu Ấn",
    description: "Gợi ý ô đặt quân tốt nhất.",
    hint: "Kích hoạt ngay.",
    success: "Đã đánh dấu nước đi!",
    border: "#d4d4d8",
    face: "#27272a",
    accent: "#f4f4f5",
    foil: "linear-gradient(135deg, #f4f4f5, #a1a1aa, #fff, #52525b)",
    artBg: "linear-gradient(160deg, #3f3f46, #d4d4d8, #18181b)",
    rarity: "common",
    deckCopies: 5,
    instant: true,
  },
  fog: {
    icon: "🌫️",
    name: "Sương Mù",
    description: "Xóa dấu hiệu trinh sát trên bàn.",
    hint: "Kích hoạt ngay.",
    success: "Sương mù che mắt đối thủ!",
    border: "#9ca3af",
    face: "#1f2937",
    accent: "#e5e7eb",
    foil: "linear-gradient(135deg, #e5e7eb, #9ca3af, #fff, #4b5563)",
    artBg: "linear-gradient(160deg, #374151, #9ca3af, #111827)",
    rarity: "common",
    deckCopies: 5,
    instant: true,
  },
  shield: {
    icon: "🛡️",
    name: "Khiên",
    description: "Bảo vệ 1 quân ○ khỏi bị xóa.",
    hint: "Chọn quân ○.",
    success: "Quân được bảo vệ!",
    border: "#38bdf8",
    face: "#082032",
    accent: "#7dd3fc",
    foil: "linear-gradient(135deg, #7dd3fc, #0ea5e9, #fff, #0369a1)",
    artBg: "linear-gradient(160deg, #0c4a6e, #38bdf8, #082f49)",
    rarity: "rare",
    deckCopies: 3,
  },
  undo: {
    icon: "↩️",
    name: "Hoàn Tác",
    description: "Hủy nước AI vừa đi.",
    hint: "Kích hoạt ngay.",
    success: "Đã hoàn tác!",
    border: "#a78bfa",
    face: "#1a0836",
    accent: "#c4b5fd",
    foil: "linear-gradient(135deg, #c4b5fd, #8b5cf6, #fff, #6d28d9)",
    artBg: "linear-gradient(160deg, #4c1d95, #a78bfa, #2e1065)",
    rarity: "rare",
    deckCopies: 3,
    instant: true,
  },
  barrier: {
    icon: "🧱",
    name: "Hàng Rào",
    description: "Phong ấn 2 ô liền kề.",
    hint: "Chọn ô trống thứ nhất.",
    success: "Hàng rào dựng xong!",
    border: "#60a5fa",
    face: "#172554",
    accent: "#93c5fd",
    foil: "linear-gradient(135deg, #93c5fd, #3b82f6, #fff, #1d4ed8)",
    artBg: "linear-gradient(160deg, #1e3a8a, #60a5fa, #172554)",
    rarity: "rare",
    deckCopies: 3,
  },
  inspire: {
    icon: "🃏",
    name: "Cảm Hứng",
    description: "Rút thêm 1 lá ngay lập tức.",
    hint: "Kích hoạt ngay.",
    success: "Đã rút thêm 1 lá!",
    border: "#f472b6",
    face: "#500724",
    accent: "#fbcfe8",
    foil: "linear-gradient(135deg, #fbcfe8, #ec4899, #fff, #9d174d)",
    artBg: "linear-gradient(160deg, #831843, #f472b6, #500724)",
    rarity: "rare",
    deckCopies: 3,
    instant: true,
  },
  grapple: {
    icon: "🪝",
    name: "Móc Kéo",
    description: "Kéo quân × sang ô trống liền kề.",
    hint: "Chọn quân ×.",
    success: "Đã kéo quân đối thủ!",
    border: "#a3e635",
    face: "#1a2e05",
    accent: "#d9f99d",
    foil: "linear-gradient(135deg, #d9f99d, #84cc16, #fff, #3f6212)",
    artBg: "linear-gradient(160deg, #365314, #a3e635, #1a2e05)",
    rarity: "rare",
    deckCopies: 3,
  },
  recall: {
    icon: "⏪",
    name: "Thu Hồi",
    description: "Rút lại nước ○ vừa đi.",
    hint: "Kích hoạt ngay.",
    success: "Đã thu hồi nước đi!",
    border: "#7dd3fc",
    face: "#0c4a6e",
    accent: "#bae6fd",
    foil: "linear-gradient(135deg, #bae6fd, #38bdf8, #fff, #0369a1)",
    artBg: "linear-gradient(160deg, #075985, #7dd3fc, #082f49)",
    rarity: "rare",
    deckCopies: 3,
    instant: true,
  },
  rust: {
    icon: "🧪",
    name: "Gỉ Sét",
    description: "Xóa khiên bảo vệ 1 quân ×.",
    hint: "Chọn quân × có khiên.",
    success: "Khiên đối thủ đã gỉ!",
    border: "#fb7185",
    face: "#4c0519",
    accent: "#fecdd3",
    foil: "linear-gradient(135deg, #fecdd3, #f43f5e, #fff, #9f1239)",
    artBg: "linear-gradient(160deg, #881337, #fb7185, #4c0519)",
    rarity: "rare",
    deckCopies: 3,
  },
  spark: {
    icon: "✴️",
    name: "Tia Lửa",
    description: "Đặt thêm 1 quân miễn phí trong lượt.",
    hint: "Kích hoạt ngay.",
    success: "Tia lửa — đặt thêm 1 quân!",
    border: "#fcd34d",
    face: "#422006",
    accent: "#fde68a",
    foil: "linear-gradient(135deg, #fde68a, #fbbf24, #fff, #b45309)",
    artBg: "linear-gradient(160deg, #78350f, #fcd34d, #451a03)",
    rarity: "rare",
    deckCopies: 3,
    instant: true,
  },
  chain: {
    icon: "⛓️",
    name: "Xích Nối",
    description: "Gỡ 1 phong ấn + khóa ô AI muốn đánh.",
    hint: "Kích hoạt ngay.",
    success: "Xích nối khóa đường AI!",
    border: "#818cf8",
    face: "#1e1b4b",
    accent: "#c7d2fe",
    foil: "linear-gradient(135deg, #c7d2fe, #6366f1, #fff, #3730a3)",
    artBg: "linear-gradient(160deg, #312e81, #818cf8, #1e1b4b)",
    rarity: "rare",
    deckCopies: 3,
    instant: true,
  },
  remove: {
    icon: "💥",
    name: "Xóa Quân",
    description: "Xóa 1 quân × (không phá khiên).",
    hint: "Chọn quân ×.",
    success: "Đã xóa quân!",
    border: "#ef4444",
    face: "#2a0a0a",
    accent: "#f87171",
    foil: "linear-gradient(135deg, #fca5a5, #ef4444, #fff, #b91c1c)",
    artBg: "linear-gradient(160deg, #7f1d1d, #ef4444, #450a0a)",
    rarity: "epic",
    deckCopies: 2,
  },
  domination: {
    icon: "🔮",
    name: "Thôn Phệ",
    description: "Biến quân × thành quân ○.",
    hint: "Chọn quân ×.",
    success: "Đã chiếm quân!",
    border: "#e879f9",
    face: "#2e1065",
    accent: "#f0abfc",
    foil: "linear-gradient(135deg, #f0abfc, #d946ef, #fff, #a21caf)",
    artBg: "linear-gradient(160deg, #701a75, #e879f9, #2e1065)",
    rarity: "epic",
    deckCopies: 2,
  },
  curse: {
    icon: "☠️",
    name: "Nguyền Rủa",
    description: "AI không dùng skill lượt tới.",
    hint: "Kích hoạt ngay.",
    success: "AI bị nguyền rủa!",
    border: "#84cc16",
    face: "#1a2e05",
    accent: "#bef264",
    foil: "linear-gradient(135deg, #bef264, #65a30d, #fff, #3f6212)",
    artBg: "linear-gradient(160deg, #365314, #84cc16, #1a2e05)",
    rarity: "epic",
    deckCopies: 2,
    instant: true,
  },
  decay: {
    icon: "💨",
    name: "Tan Rã",
    description: "Xóa mọi khiên trên bàn cờ.",
    hint: "Kích hoạt ngay.",
    success: "Mọi khiên đã tan!",
    border: "#a78bfa",
    face: "#2e1065",
    accent: "#e9d5ff",
    foil: "linear-gradient(135deg, #e9d5ff, #8b5cf6, #fff, #5b21b6)",
    artBg: "linear-gradient(160deg, #4c1d95, #a78bfa, #2e1065)",
    rarity: "epic",
    deckCopies: 2,
    instant: true,
  },
  sabotage: {
    icon: "🗡️",
    name: "Phá Hoại",
    description: "Bắt AI bỏ ngẫu nhiên 1 lá.",
    hint: "Kích hoạt ngay.",
    success: "AI mất 1 lá!",
    border: "#f97316",
    face: "#431407",
    accent: "#fed7aa",
    foil: "linear-gradient(135deg, #fed7aa, #ea580c, #fff, #9a3412)",
    artBg: "linear-gradient(160deg, #7c2d12, #f97316, #431407)",
    rarity: "epic",
    deckCopies: 2,
    instant: true,
  },
  quake: {
    icon: "🌋",
    name: "Địa Chấn",
    description: "Xóa quân theo hình chữ thập quanh ô chọn.",
    hint: "Chọn tâm chữ thập.",
    success: "Địa chấn xóa chữ thập!",
    border: "#dc2626",
    face: "#450a0a",
    accent: "#fca5a5",
    foil: "linear-gradient(135deg, #fca5a5, #dc2626, #fff, #991b1b)",
    artBg: "linear-gradient(160deg, #7f1d1d, #dc2626, #450a0a)",
    rarity: "epic",
    deckCopies: 2,
  },
  double_step: {
    icon: "⚡",
    name: "Bước Đôi",
    description: "Đặt 2 quân liên tiếp trong lượt.",
    hint: "Kích hoạt — rồi đặt 2 quân.",
    success: "Bước đôi!",
    border: "#f59e0b",
    face: "#2a1f08",
    accent: "#fbbf24",
    foil: "linear-gradient(135deg, #fbbf24, #f59e0b, #fff, #d97706)",
    artBg: "linear-gradient(160deg, #78350f, #fbbf24, #451a03)",
    rarity: "epic",
    deckCopies: 2,
    instant: true,
  },
  surge: {
    icon: "🔥",
    name: "Dồn Lực",
    description: "Đặt 2 quân + gỡ 1 phong ấn.",
    hint: "Kích hoạt — đặt 2 quân.",
    success: "Dồn lực bứt phá!",
    border: "#ea580c",
    face: "#431407",
    accent: "#fdba74",
    foil: "linear-gradient(135deg, #fdba74, #ea580c, #fff, #9a3412)",
    artBg: "linear-gradient(160deg, #7c2d12, #ea580c, #431407)",
    rarity: "epic",
    deckCopies: 2,
    instant: true,
  },
  snipe: {
    icon: "🎯",
    name: "Bắn Tỉa",
    description: "Xóa quân × — xuyên khiên.",
    hint: "Chọn quân ×.",
    success: "Bắn tỉa thành công!",
    border: "#fb923c",
    face: "#431407",
    accent: "#fdba74",
    foil: "linear-gradient(135deg, #fdba74, #f97316, #fff, #c2410c)",
    artBg: "linear-gradient(160deg, #9a3412, #fb923c, #431407)",
    rarity: "legendary",
    deckCopies: 1,
  },
  triple_step: {
    icon: "⚡⚡",
    name: "Tam Kích",
    description: "Đặt 3 quân liên tiếp trong lượt.",
    hint: "Kích hoạt — đặt 3 quân.",
    success: "Tam kích!",
    border: "#fde047",
    face: "#422006",
    accent: "#fef08a",
    foil: "linear-gradient(135deg, #fef08a, #eab308, #fff, #ca8a04)",
    artBg: "linear-gradient(160deg, #854d0e, #fde047, #422006)",
    rarity: "legendary",
    deckCopies: 1,
    instant: true,
  },
  apocalypse: {
    icon: "💀",
    name: "Diệt Vong",
    description: "Xóa sạch vùng 3×3 quanh ô chọn.",
    hint: "Chọn tâm vùng nổ.",
    success: "Vùng 3×3 đã bị xóa!",
    border: "#f43f5e",
    face: "#1a0509",
    accent: "#fb7185",
    foil: "linear-gradient(135deg, #fb7185, #e11d48, #fff, #be123c)",
    artBg: "linear-gradient(160deg, #881337, #f43f5e, #1a0509)",
    rarity: "legendary",
    deckCopies: 1,
  },
  fortify: {
    icon: "🏰",
    name: "Thành Trì",
    description: "Khiên bảo vệ TẤT CẢ quân ○.",
    hint: "Kích hoạt ngay.",
    success: "Toàn quân được khiên!",
    border: "#2dd4bf",
    face: "#042f2e",
    accent: "#5eead4",
    foil: "linear-gradient(135deg, #5eead4, #14b8a6, #fff, #0f766e)",
    artBg: "linear-gradient(160deg, #115e59, #2dd4bf, #042f2e)",
    rarity: "legendary",
    deckCopies: 1,
    instant: true,
  },
  oblivion: {
    icon: "🕳️",
    name: "Vực Thẳm",
    description: "Xóa mọi phong ấn + 1 quân × mạnh nhất.",
    hint: "Kích hoạt ngay.",
    success: "Diệt vong giáng xuống!",
    border: "#e11d48",
    face: "#0a0003",
    accent: "#fda4af",
    foil: "linear-gradient(135deg, #fda4af, #e11d48, #fff, #881337)",
    artBg: "linear-gradient(160deg, #4c0519, #e11d48, #0a0003)",
    rarity: "legendary",
    deckCopies: 1,
    instant: true,
  },
};

export const ALL_SKILL_TYPES: SkillCardType[] = Object.keys(
  SKILL_META
) as SkillCardType[];

export const AI_DIFFICULTY_CONFIG: Record<
  AiDifficulty,
  {
    label: string;
    shortLabel: string;
    depth: number;
    skillChance: number;
    maxSkillsPerTurn: number;
    topMoves: number;
    searchBranch: number;
    maxSearchNodes: number;
    searchBudgetMs: number;
    threatWeight: number;
    noise: number;
    thinkMs: number;
  }
> = {
  basic: {
    label: "Cơ bản",
    shortLabel: "CB",
    depth: 2,
    skillChance: 0.5,
    maxSkillsPerTurn: 1,
    topMoves: 11,
    searchBranch: 7,
    maxSearchNodes: 12_000,
    searchBudgetMs: 70,
    threatWeight: 1.08,
    noise: 0.18,
    thinkMs: 80,
  },
  normal: {
    label: "Trung bình",
    shortLabel: "TB",
    depth: 3,
    skillChance: 0.68,
    maxSkillsPerTurn: 1,
    topMoves: 13,
    searchBranch: 8,
    maxSearchNodes: 18_000,
    searchBudgetMs: 110,
    threatWeight: 1.14,
    noise: 0.06,
    thinkMs: 100,
  },
  hard: {
    label: "Khó",
    shortLabel: "Khó",
    depth: 4,
    skillChance: 0.9,
    maxSkillsPerTurn: 2,
    topMoves: 15,
    searchBranch: 9,
    maxSearchNodes: 26_000,
    searchBudgetMs: 160,
    threatWeight: 1.22,
    noise: 0,
    thinkMs: 130,
  },
  master: {
    label: "Cao thủ",
    shortLabel: "CT",
    depth: 5,
    skillChance: 0.98,
    maxSkillsPerTurn: 3,
    topMoves: 16,
    searchBranch: 10,
    maxSearchNodes: 36_000,
    searchBudgetMs: 220,
    threatWeight: 1.3,
    noise: 0,
    thinkMs: 160,
  },
  genius: {
    label: "Siêu đẳng",
    shortLabel: "SI",
    depth: 6,
    skillChance: 1,
    maxSkillsPerTurn: 3,
    topMoves: 18,
    searchBranch: 10,
    maxSearchNodes: 48_000,
    searchBudgetMs: 280,
    threatWeight: 1.38,
    noise: 0,
    thinkMs: 180,
  },
};

export const CARD_DRAW_MS = 480;
export const AI_SKILL_FLASH_MS = 650;

export const AI_DIFFICULTIES: AiDifficulty[] = [
  "basic",
  "normal",
  "hard",
  "master",
  "genius",
];

export const MULLIGAN_DISCARD_COUNT = 2;
