import type { CardRarity } from "./types";

export const TEXTS = {
  title: "CỜ CA RÔ",
  subtitle: "Xếp quân — chặn đối thủ — lật kèo bằng thẻ skill!",
  backHome: "← Về trang chủ",
  newGame: "Ván mới",
  cancelSkill: "Hủy thẻ",
  cancelMulligan: "Hủy đổi bài",
  playAgain: "Chơi lại",
  you: "Bạn",
  ai: "Máy AI",
  vs: "đấu",
  youWin: "Bạn thắng!",
  aiWin: "AI thắng!",
  aiThinking: "Máy đang suy nghĩ...",
  aiSkillFlash: "⚠ AI kích hoạt thẻ skill!",
  drawingCard: "Đang rút thẻ...",
  deckLabel: "Bộ bài",
  deckCount: (n: number) => `${n} lá`,
  howToPlay: "Luật chơi",
  rule1: "Nhấn ô trống để đặt quân ○ của bạn.",
  rule2: (n: number) =>
    `Ai xếp được ${n} quân liên tiếp (ngang, dọc, chéo) trước sẽ thắng.`,
  rule3: "Mỗi lượt của bạn rút 1 thẻ skill — dùng trước khi đặt quân.",
  rule4: "Tối đa 8 thẻ trên tay. Đổi 2 lá lấy 1 lá mới mỗi lượt.",
  winLengthLabel: "Điều kiện thắng",
  winLength5: "5 quân",
  winLength6: "6 quân",
  aiLevelLabel: "Cấp độ AI",
  skillHandTitle: "Tay bài",
  humanHandCount: (n: number) => `Tay bạn: ${n} thẻ`,
  aiSkillCount: (n: number) => `Tay AI: ${n} thẻ`,
  sealedCell: "Ô này đang bị phong ấn!",
  draw: "Hòa cờ!",
  doubleStepMsg: "Bước đôi! Đặt 2 quân liên tiếp trong lượt này.",
  tripleStepMsg: "Tam kích! Đặt 3 quân liên tiếp trong lượt này.",
  extraMoveMsg: "Đặt thêm 1 quân nữa!",
  extraMoveMsgMulti: (n: number) => `Còn ${n} quân nữa trong lượt!`,
  noUndoTarget: "Chưa có nước AI để hoàn tác.",
  undoDone: "Đã hoàn tác nước đi của AI!",
  shieldProtected: "Quân này được khiên bảo vệ!",
  humanWin: "Bạn thắng!",
  handFull: "Tay đầy — không rút thêm được.",
  scoutDone: (row: number, col: number) =>
    `Trinh sát: AI muốn đánh hàng ${row}, cột ${col}!`,
  barrierSecond: "Chọn ô trống liền kề để dựng hàng rào.",
  barrierAdjacent: "Ô phải liền kề ô đầu tiên!",
  swapDest: "Chọn ô trống để hoán đổi vị trí.",
  blinkSecond: "Chọn quân ○ thứ hai để hoán vị.",
  grappleDest: "Chọn ô trống liền kề để kéo quân ×.",
  peekDone: (preview: string) => `Lá tới: ${preview}`,
  noRecallTarget: "Chưa có nước ○ để thu hồi.",
  mendNoShield: "Quân này không có khiên.",
  rustNoShield: "Quân × không có khiên.",
  unsealInvalid: "Ô này không bị phong ấn.",
  sparkMsg: "Tia lửa! Đặt thêm 1 quân trong lượt.",
  surgeMsg: "Dồn lực! Đặt 2 quân và gỡ 1 phong ấn.",
  markDone: (row: number, col: number) =>
    `Dấu ấn: nên đánh hàng ${row}, cột ${col}!`,
  sabotageEmpty: "Tay AI trống — không phá hoại được.",
  oblivionNoTarget: "Không có quân × để xóa.",
  mulligan: "Đổi 2 → 1",
  mulliganPick: (n: number) => `Chọn ${n} lá để bỏ (đổi lấy 1 lá mới)`,
  mulliganDone: "Đã đổi bài!",
  codexTitle: "📖 Bộ sưu tập thẻ",
  codexSubtitle: (total: number) =>
    `${total} lá trong bộ — tỉ lệ rơi theo độ hiếm`,
  soundOn: "🔊 Âm thanh",
  soundOff: "🔇 Tắt tiếng",
  codexRarityHint: (r: CardRarity) => {
    const hints: Record<CardRarity, string> = {
      common: "Thường gặp, hiệu ứng cơ bản",
      rare: "Hiếm, lợi thế chiến thuật",
      epic: "Sử thi, đảo chiều cục",
      legendary: "👑 Vua — skill siêu mạnh",
    };
    return hints[r];
  },
} as const;
